// Swift bridging header — exposes the C ABI from libtorah_search.a to the
// Swift module. The header itself ships inside TorahSearch.xcframework as
// `tantivy_bridge.h` (generated by cbindgen via build-ios.sh), so this just
// re-imports it.

#import "tantivy_bridge.h"

#import <React/RCTBridgeModule.h>
